version: "3.9"
services:
  app:
    build: .
    container_name: abseits-calendar
    environment:
      - CALDAV_URL=https://cloud.lemat.de/remote.php/dav
      - CALDAV_CALENDAR=Test
      - CALDAV_USER=lennard0711
      - ABSEITS_UID=400000000205
      - ABSEITS_KADER=BZL
      - ABSEITS_USER=lennard indlekofer
    env_file: .env