version: "3.9"
services:
  app:
    build: .
    container_name: abseits-calendar
    environment:
      - CALDAV_URL=https://nextcloud.example.com/remote.php/dav
      - CALDAV_CALENDAR=Abseits
      - CALDAV_USER=nutzername
      - ABSEITS_UID=replaceme
      - ABSEITS_KADER=BZL
      - ABSEITS_USER=vorname nachname
    env_file: .env